default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      role: accountadmin
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      private_key: "{{ env_var('SNOWFLAKE_PRIVATE_KEY') }}"
      warehouse: d_harato_wh
      database: d_harato_db
      schema: elementary
      threads: 8
    prd:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      role: accountadmin
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      private_key: "{{ env_var('SNOWFLAKE_PRIVATE_KEY') }}"
      warehouse: d_harato_wh
      database: d_harato_db
      schema: elementary
      threads: 8

elementary:
  outputs:
    default:
      type: snowflake
      account: ar29333.ap-northeast-1.aws
      user: d.harato@datumstudio.jp
      private_key: "{{ env_var('SNOWFLAKE_PRIVATE_KEY') }}"
      role: accountadmin
      warehouse: d_harato_wh
      database: d_harato_db
      schema: elementary
      threads: 8