name: Comment PR with fixed message (using PAT)

permissions:
  issues: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  comment-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create fixed comment file
        run: |
          cat <<EOF > comment.md
          This is a fixed comment.
          Please check the run details at: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          EOF
          cat comment.md

      - name: Set comment as output
        id: get_comment
        run: |
          comment=$(cat comment.md)
          echo "comment<<EOF" >> $GITHUB_OUTPUT
          echo "$comment" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post fixed comment to PR using PAT
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.get_comment.outputs.comment }}