name: Run dbt-profiler on push

on:
  push:
    branches:
      - main

jobs:
  run-dbt-profiler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-snowflake dbt-profiler

      - name: Show repository structure
        run: |
          echo "Current directory:"
          pwd
          echo "Listing directory contents:"
          ls -la

      - name: Run dbt build & dbt-profiler and capture output
        id: profiler
        working-directory: sample_project
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
        run: |
          # ビルド実行（必要に応じて）
          dbt build --target prd
          # dbt-profiler の実行結果を変数にキャプチャ
          output=$(dbt-profiler --target prd)
          echo "dbt-profiler output:"
          echo "$output"
          # GitHub Actions の出力変数に設定（※ set-output は非推奨なので $GITHUB_OUTPUT を利用）
          echo "profiler_output<<EOF" >> $GITHUB_OUTPUT
          echo "$output" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post dbt-profiler result as a commit comment
        uses: actions/github-script@v6
        env:
          PROFILER_OUTPUT: ${{ steps.profiler.outputs.profiler_output }}
        with:
          script: |
            const commentBody = `## dbt-profiler Result\n\n\`\`\`markdown\n${process.env.PROFILER_OUTPUT}\n\`\`\``;
            await github.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: commentBody,
            });