name: Upload dbt Files to S3

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  upload_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Upload dbt_project.yml to S3
        run: |
          aws s3 cp github/dbt/sample_project/dbt_project.yml s3://harato-trocco-dbt-snow/dbt_project.yml --acl private

      - name: Upload catalog.json to S3
        run: |
          aws s3 cp github/dbt/sample_project/target/manifest.json s3://harato-trocco-dbt-snow/target/catalog.json --acl private